# CS 4820
# Lab 4: Understanding how a _feed-forward_ ANN works

In this lab, we are going to manually calculate the outputs of all the neurons in a multi-layer feed_forwared NN and then build a Teras model to verify our calculations.

### 0. Manually calculate the outputs from all neurons

In [5]:
# Your code here
import tensorflow as tf
import numpy as np
from tensorflow.keras.activations import tanh
from tensorflow.keras.activations import sigmoid


x = np.array([[.5, 1.2, 0.7]])

w1 = np.array([[1, 0],
              [-1, 1],
              [0, -1]])

theta1 = np.full((2,),0.01)

output1 = tanh(np.matmul(x, w1) + theta1)

w2 = np.array([[-1],
               [-.8]])

theta2 = np.full((1,), 0.1)

output2 = sigmoid(np.matmul(output1, w2) + theta2)

print(output2)

print('Inputs:\n', x, '\n')
print('Weights:\n', w1, '\n')
print('Thetas (bias):\n', theta1, '\n')
print('Output of hidden layer:\n', output1.numpy(), '\n')
print('Weights from hidden layer to output layer:\n', w2, '\n')
print('Theta (bias) of output layer:\n', theta2, '\n')
print('Output of entire neural network:\n', output2.numpy(), '\n')

tf.Tensor([[0.57981789]], shape=(1, 1), dtype=float64)
Inputs:
 [[0.5 1.2 0.7]] 

Weights:
 [[ 1  0]
 [-1  1]
 [ 0 -1]] 

Thetas (bias):
 [0.01 0.01] 

Output of hidden layer:
 [[-0.597982   0.4699452]] 

Weights from hidden layer to output layer:
 [[-1. ]
 [-0.8]] 

Theta (bias) of output layer:
 [0.1] 

Output of entire neural network:
 [[0.57981789]] 



### 1. Build a model in Keras to verify the calculations above

In [6]:
# Your code here
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.optimizers import Adam

model = Sequential()
model.add(Dense(2, input_shape=(3,), activation='tanh'))
model.add(Dense(1, activation='sigmoid'))
model.compile(Adam(lr=0.1),
              loss='binary_crossentropy',
              metrics=['accuracy'])

model.layers[0].set_weights([w1,theta1])
model.layers[1].set_weights([w2,theta2])

print('Karas Model Prediction of input:\n', x, '\n is:\n', model.predict(x))

Karas Model Prediction of input:
 [[0.5 1.2 0.7]] 
 is:
 [[0.5798179]]
